project:
  type: book
  output-dir: docs
  
book:
  title: "Estadística para el Análisis Político 1"
  author: "Christian Chiroque"
  favicon: pucp.jpg
  date: "3/17/2024"
  chapters:
    - index.qmd
    - s1_intro.qmd
    - references.qmd
  
bibliography: references.bib

format:
  html:
    theme: 
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt
lang: es

editor: visual

