project:
  type: book
  output-dir: docs
  
book:
  title: "Estadística para el Análisis Político 1"
  author: "Christian Chiroque"
  cover-image: portada.png
  favicon: quipu.png
  date: "4/4/2024"
  sidebar: 
    logo: quipu2.png
    search: true
  chapters:
    - index.qmd
    - s1_intro.qmd
    - s2_manipulacion.qmd
    - s3_descriptiva.qmd
    - s4_introInferencia.qmd

bibliography: references.bib

format:
  html:
    theme: 
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt
lang: es

editor: visual

filters: 
  - webr