# Sobre el curso {.unnumbered}

## Bienvenida

Hola! Bienvenid\@ al curso de **Estadística para el Análisis Político 1** de la especialidad de Ciencia Política y Gobierno de la Pontificia Universidad Católica del Perú.

En esta página podrás encontrar toda la información referida al curso tal como: presentaciones (ppt), código, texto explicativo y material audiovisual adicional..

## Sílabo

```{=html}
<iframe src="files/silabo.pdf" width="700" height="500" style="border: none;"></iframe>
```
## Sobre IA generativa

Permitimos y promovemos activamente el uso de inteligencia artificial generativa, como ChatGPT, Gemini, y otras plataformas similares, como soporte para la creación y sofisticación del código en R.

Creemos firmemente que estas herramientas pueden ser aliados significativos para profundizar en la comprensión de conceptos complejos, mejorar las habilidades de programación y fomentar la innovación y creatividad en nuestros proyectos y tareas.

La integración de la inteligencia artificial en nuestro proceso de aprendizaje ofrece una oportunidad única para experimentar con nuevas formas de resolver problemas, optimizar procesos y generar ideas que puedan llevar nuestra capacidad analítica y técnica a nuevos niveles.

Sin embargo, es importante destacar que, mientras fomentamos el uso de estas herramientas tecnológicas avanzadas para la exploración y el aprendizaje durante el curso, no se permitirá su uso en las evaluaciones.

## Sobre el R y R Studio

Tanto en las sesiones teóricas, como en las prácticas, se hará uso del software libre R y de la interfase Rstudio. Se requiere descargar las últimas versiones de ambos programas informáticos.

La última versión de R (4.3.3) puede ser descargada gratuitamente para Windows o macOS.

<https://cran.r-project.org/bin/windows/base/>

<https://cran.r-project.org/bin/macosx/>

La última versión de Rstudio Desktop (versión RStudio 2023.12.1+402) puede ser descargada aquí para Windows o macOS.

<https://posit.co/download/rstudio-desktop/>

## Sobre el trabajo grupal

### Indicaciones

```{=html}
<iframe src="files/trabajo_grupal.pdf" width="700" height="500" style="border: none;"></iframe>
```
### Lugares ricos en datos

Aquí te dejo algunas recomendaciones sobre lugares ricos en datos donde podrás encontrar datasets de insumo para construir tu base de datos.

```{=html}
<iframe src="files/lugares_ricos_en_datos.pdf" width="700" height="500" style="border: none;"></iframe>
```
